#include<bits/stdc++.h>
using namespace std;
int main(){
    //string a;
//cout<<"gsihpvphsvphv \n";
//cout<<"hello world"<<endl;
//cout<<"enter the name "<<endl;
//cin>>a;
//cout<<"the user name is "<<a;



//int store whole number and negative whole number 
//float stores decimal
//char stores  single character 
//double stores many digit of decimal
//string which stores collection of character 
//int a=2;
//float b=3.3;
//char c='a';
//double d=3.9372087;
//string e="NITESH";
//cout<<setprecision(9)<<d;
//cout<<a<<endl<<b<<endl<<c<<endl<<d<<endl<<e;

//= and ==
//if (2+2==4)
//{
//cout<<"this is equal digit";
//}
//else
//{
//    cout<<"this is not equal";

//}

int a;
cout<<"enter the mark";
cin>>a;
if (a>=90)
{
    cout<<"o grade";
}

if (a>=80)
{
    cout<<"e grade";
}

if (a>=70)
{
    cout<<"a grade";

}
else
{
    cout<<"b grade ";

}




return 0;
}